development:
  adapter: postgresql
  encoding: unicode
  database: teacher_rating_development
  pool: 5
  username: nykdev
  password: nykdev

test:
  adapter: postgresql
  encoding: unicode
  database: teacher_rating_test
  pool: 5
  username: nykdev
  password: nykdev
